# /etc/netmon-agent/config.yaml
router_id: "router-01"
rails_base_url: "http://10.0.0.10:3000"
auth_token: "secret"

nflog_groups: [10, 11]
dnsmasq_log_path: "/var/log/dnsmasq.log"

lan_interfaces: ["enp3s0"]
wan_interfaces: ["enp2s0"]
lan_subnets: ["10.0.0.0/24"]

metrics_bind: "127.0.0.1:9109"

batch_max_events: 250
batch_max_wait: 1s
queue_depth: 2000

spool_dir: "/var/lib/netmon-agent/spool"
spool_max_bytes: 52428800

qname_hash_salt: "secret"
qname_hash_cap: 200
emit_conntrack_new: false


lsmod | rg "nfnetlink|nfnetlink_log|nf_log|nflog"
modprobe nfnetlink
modprobe nfnetlink_log
modprobe nf_log
modprobe nflog
