local_subnets:
  - 10.0.0.0/24

common_ports:
  - 53
  - 80
  - 123
  - 443

new_window_seconds: 600

common_protos:
  - tcp
  - udp

anomaly_threshold: 50
dedup_suppress_seconds: 600
baseline_window_minutes: 60
dormant_remote_days: 30
high_fanout_threshold: 30
high_unique_ports_threshold: 20

alert:
  threshold_score: 70
  required_codes:
    - RARE_PORT
    - UNEXPECTED_PROTO
    - HIGH_EGRESS
    - HIGH_FANOUT
  suppress_if_only_codes:
    - NO_RDNS
  incident_window_seconds: 600
  incident_dedup_seconds: 600

exclude_subnets:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 127.0.0.0/8
  - 169.254.0.0/16

interfaces:
  - enp42s0
  - enp2s0
  - enp3s0
